export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const REQUEST_TWEETS = "REQUEST_TWEETS";
export const REQUEST_TWEETS_ERROR = "REQUEST_TWEETS_ERROR";
export const REQUEST_TWEETS_SUCCESS = "REQUEST_TWEETS_SUCCESS";

export const REQUEST_USER_TWEETS = "REQUEST_USER_TWEETS";
export const REQUEST_USER_TWEETS_ERROR = "REQUEST_USER_TWEETS_ERROR";
export const REQUEST_USER_TWEETS_SUCCESS = "REQUEST_USER_TWEETS_SUCCESS";

export const POST_TWEET = "POST_TWEET";
export const POST_TWEET_SUCCESS = "POST_TWEET_SUCCESS";
export const POST_TWEET_ERROR = "POST_TWEET_ERROR";

export const REQUEST_USER = "REQUEST_USER";
export const REQUEST_USER_SUCCESS = "REQUEST_USER_SUCCESS";
export const REQUEST_USER_ERROR = "REQUEST_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
