export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const REQUEST_POSTS = "REQUEST_POSTS";
export const REQUEST_POSTS_ERROR = "REQUEST_POSTS_ERROR";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";

export const REQUEST_USER_POSTS = "REQUEST_USER_POSTS";
export const REQUEST_USER_POSTS_ERROR = "REQUEST_USER_POSTS_ERROR";
export const REQUEST_USER_POSTS_SUCCESS = "REQUEST_USER_POSTS_SUCCESS";

export const POST_POST = "POST_POST";
export const POST_POST_SUCCESS = "POST_POST_SUCCESS";
export const POST_POST_ERROR = "POST_POST_ERROR";

export const REQUEST_USER = "REQUEST_USER";
export const REQUEST_USER_SUCCESS = "REQUEST_USER_SUCCESS";
export const REQUEST_USER_ERROR = "REQUEST_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const GET_COMMENT_POST = "GET_COMMENT_POST";
export const GET_COMMENT_POST_SUCCESS = "GET_COMMENT_POST_SUCCESS";
export const GET_COMMENT_POST_ERROR = "GET_COMMENT_POST_ERROR";

export const COMMENT_POST = "COMMENT_POST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_ERROR = "COMMENT_POST_ERROR";

export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";

export const SHARE_POST = "SHARE_POST";
export const SHARE_POST_SUCCESS = "SHARE_POST_SUCCESS";
export const SHARE_POST_ERROR = "SHARE_POST_ERROR";

export const GET_LIKE_POST = "GET_LIKE_POST";
export const GET_LIKE_POST_SUCCESS = "GET_LIKE_POST_SUCCESS";
export const GET_LIKE_POST_ERROR = "LIKE_POST_ERROR";

export const GET_SHARE_POST = "GET_SHARE_POST";
export const GET_SHARE_POST_SUCCESS = "GET_SHARE_POST_SUCCESS";
export const GET_SHARE_POST_ERROR = "GET_SHARE_POST_ERROR";
